global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'coopcredit-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['credit-application-service:8080', 'risk-central-service:8081']
